# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from service_spec import smart_bus_pb2 as service__spec_dot_smart__bus__pb2


class SmartBusStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.checkTicket = channel.unary_unary(
                '/SmartBus/checkTicket',
                request_serializer=service__spec_dot_smart__bus__pb2.checkTicketInputs.SerializeToString,
                response_deserializer=service__spec_dot_smart__bus__pb2.checkTicketOutput.FromString,
                )
        self.checkTicketOff = channel.unary_unary(
                '/SmartBus/checkTicketOff',
                request_serializer=service__spec_dot_smart__bus__pb2.checkTicketInputs.SerializeToString,
                response_deserializer=service__spec_dot_smart__bus__pb2.checkTicketOutput.FromString,
                )


class SmartBusServicer(object):
    """Missing associated documentation comment in .proto file."""

    def checkTicket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def checkTicketOff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SmartBusServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'checkTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.checkTicket,
                    request_deserializer=service__spec_dot_smart__bus__pb2.checkTicketInputs.FromString,
                    response_serializer=service__spec_dot_smart__bus__pb2.checkTicketOutput.SerializeToString,
            ),
            'checkTicketOff': grpc.unary_unary_rpc_method_handler(
                    servicer.checkTicketOff,
                    request_deserializer=service__spec_dot_smart__bus__pb2.checkTicketInputs.FromString,
                    response_serializer=service__spec_dot_smart__bus__pb2.checkTicketOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SmartBus', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SmartBus(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def checkTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SmartBus/checkTicket',
            service__spec_dot_smart__bus__pb2.checkTicketInputs.SerializeToString,
            service__spec_dot_smart__bus__pb2.checkTicketOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def checkTicketOff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SmartBus/checkTicketOff',
            service__spec_dot_smart__bus__pb2.checkTicketInputs.SerializeToString,
            service__spec_dot_smart__bus__pb2.checkTicketOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
