# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_spec/smart_bus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cservice_spec/smart_bus.proto\x1a\x1bgoogle/protobuf/empty.proto\"%\n\x11\x63heckTicketOutput\x12\x10\n\x08response\x18\x01 \x01(\t\"9\n\x11\x63heckTicketInputs\x12\x11\n\tticket_id\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\t2\x7f\n\x08SmartBus\x12\x37\n\x0b\x63heckTicket\x12\x12.checkTicketInputs\x1a\x12.checkTicketOutput\"\x00\x12:\n\x0e\x63heckTicketOff\x12\x12.checkTicketInputs\x1a\x12.checkTicketOutput\"\x00\x62\x06proto3')



_CHECKTICKETOUTPUT = DESCRIPTOR.message_types_by_name['checkTicketOutput']
_CHECKTICKETINPUTS = DESCRIPTOR.message_types_by_name['checkTicketInputs']
checkTicketOutput = _reflection.GeneratedProtocolMessageType('checkTicketOutput', (_message.Message,), {
  'DESCRIPTOR' : _CHECKTICKETOUTPUT,
  '__module__' : 'service_spec.smart_bus_pb2'
  # @@protoc_insertion_point(class_scope:checkTicketOutput)
  })
_sym_db.RegisterMessage(checkTicketOutput)

checkTicketInputs = _reflection.GeneratedProtocolMessageType('checkTicketInputs', (_message.Message,), {
  'DESCRIPTOR' : _CHECKTICKETINPUTS,
  '__module__' : 'service_spec.smart_bus_pb2'
  # @@protoc_insertion_point(class_scope:checkTicketInputs)
  })
_sym_db.RegisterMessage(checkTicketInputs)

_SMARTBUS = DESCRIPTOR.services_by_name['SmartBus']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHECKTICKETOUTPUT._serialized_start=61
  _CHECKTICKETOUTPUT._serialized_end=98
  _CHECKTICKETINPUTS._serialized_start=100
  _CHECKTICKETINPUTS._serialized_end=157
  _SMARTBUS._serialized_start=159
  _SMARTBUS._serialized_end=286
# @@protoc_insertion_point(module_scope)
